
--- Extraindo dados de Produtos da Fonte/Source
--- Fonte: Banco de dados Firebird

SELECT P.CODIGO , P.DESCRICAO , P.CATEGORIA AS COD_CATEGORIA, C.DESCRICAO AS NM_CATEGORIA , P.MARCA AS COD_MARCA , M2.DESCRICAO AS NM_MARCA ,PR.PRECO AS PRECO_UNI_CUSTO, PR2.PRECO AS PRECO_UN_VENDA FROM PRODUTOS P
left JOIN CATEGORIAS C ON P.CATEGORIA = C."CODIGO" 
LEFT JOIN PRECOS_PROD_SERV PR ON P.CODIGO=PR.PRODUTO
LEFT JOIN PRECOS_PROD_SERV PR2 ON P.CODIGO=PR2.PRODUTO 
LEFT JOIN MARCAS M2 ON P.MARCA=M2.CODIGO
--LEFT JOIN PRODS_ESTOQ_IMP_OUTR peio ON p."CODIGO" = peio.PRODUTO 
WHERE --P.ATIVO='S'
PR.TABELA = 1
AND PR2.TABELA = 2;