
--- Extraindo dados de FATO_Venda da Fonte/Source
--- Fonte: Banco de dados Firebird

SELECT 
V2."DATA" ,
v.CODIGOMESTRE AS COD_VENDA, 
V2.OPERADOR AS VENDEDOR, 
v2.CLIENTE , 
V."QUANTIDADE" , 
V.PRODUTO, V.UNITARIO , 
V.DESCONTO , 
V.SUBTOTAL , 
(v.SUBTOTAL - v.DESCONTO ) AS TOTALPAGO,
V2.PARCELADO ,
V2.A_VISTA_CART_DEB , 
V2.A_VISTA_CART_CRED , 
V2.A_PRAZO_CART_CRED ,  
V2."REFERENCIA" , 
V2.HISTORICO, 
V2.MODULO_ORIGEM,
v3.TIPO ,
v3."VALOR" ,
v3.QTDE_PARC ,
v3.OPERADORA ,
v3.BANDEIRA 
FROM VENDADETALHE v 
INNER JOIN VENDAMESTRE v2 ON v.CODIGOMESTRE = v2.CODIGOMESTRE
INNER JOIN VENDARCBTOS v3 ON v.CODIGOMESTRE = v3.CODIGOMESTRE 
WHERE v2.SITUACAO = '3 - Autorizada';

-- OBS: Data de corte para extração dos dados definimos aqui.

